### PR TITLE
feat: add option to configure path prefix

### LINKED ISSUE #7: Add option to disable the path prefix
@khan100:

> Is it possible to disable the /cyberpunkpay/ subpath? I would prefer clean urls with only a subdomain e.g. `https://pay.example.com/donations`

### PR DESCRIPTION
**Pull request by khand100**
I tried to implement the removal of the path prefix myself.
When setting the new option `path_prefix` to `/` the prefix is removed. The default still is `cypherpunkpay`.
Looks like everything still works, but I was unsure how to write a test where the path_prefix is set to `/`.
Maybe you have an idea?

Closes #7

### CODE REVIEW

**Comment by CypherpunkDev** [comment]
Thanks so much!

I fixed some remaining issues with this proposed implementation in the next commit. Please note the config section changed from expert to server.

**Comment by khand100** [comment]
Thanks for the merge.

But why did you remove the check if the prefix contains a slash?
Yes it was an artificial limit to only allow 1 folder depth, but only with 1 level in depth the redirects work at all depths.
And more importantly the path can not end with a slash because it will break the admin login (because of how the path is build here [cypherpunkpay/\_\_init\_\_.py#L71](https://github.com/CypherpunkPay/CypherpunkPay/blob/master/cypherpunkpay/__init__.py#L71)). The check saved users from misconfiguring it.

**Comment by CypherpunkDev** [comment]
Thanks for verifying! I wasn't fully aware of the significance of this check.

I removed it to allow the `/prefix` value. I will revisit this.

**Comment by CypherpunkDev** [comment]
It should be fixed now.

**Pull request merged**
